### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by Kriechi** [voxpupuli/puppet-fail2ban#28]
I'm getting the following deprecation warnings when running Puppet 4.10 and puppet-fail2ban 1.3.4:

```
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Pattern[]. There is further documentation for validate_legacy function in the README. at [".../fail2ban/manifests/init.pp", 40]
   (at .../stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README. at [".../fail2ban/manifests/init.pp", 41]
   (at .../stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Absolute_Path. There is further documentation for validate_legacy function in the README. at [".../fail2ban/manifests/init.pp", 44]
   (at .../stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README. at [".../fail2ban/manifests/init.pp", 45]
   (at .../stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Hash. There is further documentation for validate_legacy function in the README. at [".../fail2ban/manifests/init.pp", 60]
   (at .../stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: The function 'hiera_hash' is deprecated in favor of using 'lookup'. See https://docs.puppet.com/puppet/4.10/reference/deprecated_language.html
   (file & line not available)
```

Looks like it is time to upgrade a few things?

**Comment by dhoppe** [comment]
This has been solved by #110
